sudo: required
services:
    - docker

script:
    - docker build -t Jaleleddine/cicd_fullstack .
    - docker images Jaleleddine/cicd_fullstack
before_deploy:
  - docker login -u hajlaoui -p Hajlaoui2019@
deploy: 
  provider: script 
  script: docker push Jaleleddine/cicd_fullstack
  on:
    branch: master
    
