sudo: required
services:
    - docker

script:
    - docker build -t imagenodejs .
    - docker images imagenodejs
before_deploy:
  - docker login -u hajlaoui -p Hajlaoui2019@
deploy: 
  provider: script 
  script: docker push hajlaoui/imagenodejs:v10
  on:
    branch: master   
    
