sudo: required
services:
    - docker

script:
    - docker build -t hajlaoui/node2 .
    - docker images hajlaoui/node2
before_deploy:
  - docker login -u hajlaoui -p Hajlaoui2019@
deploy: 
  provider: script 
  script: docker push hajlaoui/node2:v10
  on:
    branch: master 
    
